CREATE TABLE IF NOT EXISTS sys_inspection (
  id INT PRIMARY KEY AUTO_INCREMENT,
  pid VARCHAR(100),
  inspection_user VARCHAR(100),
  guardian_user VARCHAR(100),
  inspection_time DATETIME,
  first_url VARCHAR(500),
  second_url VARCHAR(500),
  third_url VARCHAR(500),
  fourth_url VARCHAR(500),
  fifth_url VARCHAR(500),
  appearance_url VARCHAR(500),
  earlier_url VARCHAR(500),
  later_url VARCHAR(500),
  switch_model VARCHAR(100),
  current_rating VARCHAR(100),
  traverse_section VARCHAR(100),
  supply_voltage VARCHAR(100),
  a_starting VARCHAR(100),
  a_running VARCHAR(100),
  b_starting VARCHAR(100),
  b_running VARCHAR(100),
  c_starting VARCHAR(100),
  c_running VARCHAR(100),
  remark VARCHAR(255)
);
