-- v1.96: 依据 PDF 17-26 页，重建维保宽表字段（含完整序号范围）

DROP TABLE IF EXISTS sys_box_maintenance_monthly;
DROP TABLE IF EXISTS sys_box_maintenance_quarterly;
DROP TABLE IF EXISTS sys_box_maintenance_yearly;

CREATE TABLE sys_box_maintenance_monthly (
  id INT PRIMARY KEY AUTO_INCREMENT,
  box_id INT NOT NULL,
  supervise_user VARCHAR(100),
  maintenance_user VARCHAR(100),
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  m1_result TEXT, m1_status TEXT, m1_remark TEXT,
  m2_result TEXT, m2_status TEXT, m2_remark TEXT,
  m3_result TEXT, m3_status TEXT, m3_remark TEXT,
  m4_result TEXT, m4_status TEXT, m4_remark TEXT,
  m5_result TEXT, m5_status TEXT, m5_remark TEXT,
  m6_result TEXT, m6_status TEXT, m6_remark TEXT,
  m7_result TEXT, m7_status TEXT, m7_remark TEXT,
  m8_result TEXT, m8_status TEXT, m8_remark TEXT,
  m9_result TEXT, m9_status TEXT, m9_remark TEXT,
  m10_result TEXT, m10_status TEXT, m10_remark TEXT,
  m11_result TEXT, m11_status TEXT, m11_remark TEXT,
  m12_result TEXT, m12_status TEXT, m12_remark TEXT,
  m13_result TEXT, m13_status TEXT, m13_remark TEXT,
  m14_result TEXT, m14_status TEXT, m14_remark TEXT,
  m15_result TEXT, m15_status TEXT, m15_remark TEXT,
  m16_result TEXT, m16_status TEXT, m16_remark TEXT,
  m17_result TEXT, m17_status TEXT, m17_remark TEXT,
  m18_result TEXT, m18_status TEXT, m18_remark TEXT,
  m19_result TEXT, m19_status TEXT, m19_remark TEXT,
  m20_result TEXT, m20_status TEXT, m20_remark TEXT,
  m21_result TEXT, m21_status TEXT, m21_remark TEXT,
  m22_result TEXT, m22_status TEXT, m22_remark TEXT,
  m23_result TEXT, m23_status TEXT, m23_remark TEXT,
  m24_result TEXT, m24_status TEXT, m24_remark TEXT,
  m25_result TEXT, m25_status TEXT, m25_remark TEXT,
  m26_result TEXT, m26_status TEXT, m26_remark TEXT,
  m27_result TEXT, m27_status TEXT, m27_remark TEXT,
  m28_result TEXT, m28_status TEXT, m28_remark TEXT,
  m29_result TEXT, m29_status TEXT, m29_remark TEXT,
  m30_result TEXT, m30_status TEXT, m30_remark TEXT,
  m31_result TEXT, m31_status TEXT, m31_remark TEXT,
  m32_result TEXT, m32_status TEXT, m32_remark TEXT,
  m33_result TEXT, m33_status TEXT, m33_remark TEXT,
  m34_result TEXT, m34_status TEXT, m34_remark TEXT,
  m35_result TEXT, m35_status TEXT, m35_remark TEXT,
  m36_result TEXT, m36_status TEXT, m36_remark TEXT,
  INDEX idx_bmm_box_id (box_id),
  INDEX idx_bmm_created_time (created_time)
);

CREATE TABLE sys_box_maintenance_quarterly (
  id INT PRIMARY KEY AUTO_INCREMENT,
  box_id INT NOT NULL,
  supervise_user VARCHAR(100),
  maintenance_user VARCHAR(100),
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  q1_result TEXT, q1_status TEXT, q1_remark TEXT,
  q2_result TEXT, q2_status TEXT, q2_remark TEXT,
  q3_result TEXT, q3_status TEXT, q3_remark TEXT,
  q4_result TEXT, q4_status TEXT, q4_remark TEXT,
  q5_result TEXT, q5_status TEXT, q5_remark TEXT,
  q6_result TEXT, q6_status TEXT, q6_remark TEXT,
  q7_result TEXT, q7_status TEXT, q7_remark TEXT,
  q8_result TEXT, q8_status TEXT, q8_remark TEXT,
  q9_result TEXT, q9_status TEXT, q9_remark TEXT,
  q10_result TEXT, q10_status TEXT, q10_remark TEXT,
  q11_result TEXT, q11_status TEXT, q11_remark TEXT,
  q12_result TEXT, q12_status TEXT, q12_remark TEXT,
  q13_result TEXT, q13_status TEXT, q13_remark TEXT,
  q14_result TEXT, q14_status TEXT, q14_remark TEXT,
  q15_result TEXT, q15_status TEXT, q15_remark TEXT,
  q16_result TEXT, q16_status TEXT, q16_remark TEXT,
  q17_result TEXT, q17_status TEXT, q17_remark TEXT,
  q18_result TEXT, q18_status TEXT, q18_remark TEXT,
  q19_result TEXT, q19_status TEXT, q19_remark TEXT,
  q20_result TEXT, q20_status TEXT, q20_remark TEXT,
  q21_result TEXT, q21_status TEXT, q21_remark TEXT,
  q22_result TEXT, q22_status TEXT, q22_remark TEXT,
  q23_result TEXT, q23_status TEXT, q23_remark TEXT,
  q24_result TEXT, q24_status TEXT, q24_remark TEXT,
  q25_result TEXT, q25_status TEXT, q25_remark TEXT,
  q26_result TEXT, q26_status TEXT, q26_remark TEXT,
  q27_result TEXT, q27_status TEXT, q27_remark TEXT,
  q28_result TEXT, q28_status TEXT, q28_remark TEXT,
  q29_result TEXT, q29_status TEXT, q29_remark TEXT,
  q30_result TEXT, q30_status TEXT, q30_remark TEXT,
  q31_result TEXT, q31_status TEXT, q31_remark TEXT,
  q32_result TEXT, q32_status TEXT, q32_remark TEXT,
  q33_result TEXT, q33_status TEXT, q33_remark TEXT,
  q34_result TEXT, q34_status TEXT, q34_remark TEXT,
  q35_result TEXT, q35_status TEXT, q35_remark TEXT,
  q36_result TEXT, q36_status TEXT, q36_remark TEXT,
  q37_result TEXT, q37_status TEXT, q37_remark TEXT,
  q38_result TEXT, q38_status TEXT, q38_remark TEXT,
  q39_result TEXT, q39_status TEXT, q39_remark TEXT,
  q40_result TEXT, q40_status TEXT, q40_remark TEXT,
  q41_result TEXT, q41_status TEXT, q41_remark TEXT,
  q42_result TEXT, q42_status TEXT, q42_remark TEXT,
  q43_result TEXT, q43_status TEXT, q43_remark TEXT,
  q44_result TEXT, q44_status TEXT, q44_remark TEXT,
  q45_result TEXT, q45_status TEXT, q45_remark TEXT,
  q46_result TEXT, q46_status TEXT, q46_remark TEXT,
  q47_result TEXT, q47_status TEXT, q47_remark TEXT,
  q48_result TEXT, q48_status TEXT, q48_remark TEXT,
  q49_result TEXT, q49_status TEXT, q49_remark TEXT,
  q50_result TEXT, q50_status TEXT, q50_remark TEXT,
  q51_result TEXT, q51_status TEXT, q51_remark TEXT,
  q52_result TEXT, q52_status TEXT, q52_remark TEXT,
  q53_result TEXT, q53_status TEXT, q53_remark TEXT,
  q54_result TEXT, q54_status TEXT, q54_remark TEXT,
  q55_result TEXT, q55_status TEXT, q55_remark TEXT,
  q56_result TEXT, q56_status TEXT, q56_remark TEXT,
  q57_result TEXT, q57_status TEXT, q57_remark TEXT,
  INDEX idx_bmq_box_id (box_id),
  INDEX idx_bmq_created_time (created_time)
);

CREATE TABLE sys_box_maintenance_yearly (
  id INT PRIMARY KEY AUTO_INCREMENT,
  box_id INT NOT NULL,
  supervise_user VARCHAR(100),
  maintenance_user VARCHAR(100),
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  y1_result TEXT, y1_status TEXT, y1_remark TEXT,
  y2_result TEXT, y2_status TEXT, y2_remark TEXT,
  y3_result TEXT, y3_status TEXT, y3_remark TEXT,
  y4_result TEXT, y4_status TEXT, y4_remark TEXT,
  y5_result TEXT, y5_status TEXT, y5_remark TEXT,
  y6_result TEXT, y6_status TEXT, y6_remark TEXT,
  y7_result TEXT, y7_status TEXT, y7_remark TEXT,
  y8_result TEXT, y8_status TEXT, y8_remark TEXT,
  y9_result TEXT, y9_status TEXT, y9_remark TEXT,
  y10_result TEXT, y10_status TEXT, y10_remark TEXT,
  y11_result TEXT, y11_status TEXT, y11_remark TEXT,
  y12_result TEXT, y12_status TEXT, y12_remark TEXT,
  y13_result TEXT, y13_status TEXT, y13_remark TEXT,
  y14_result TEXT, y14_status TEXT, y14_remark TEXT,
  y15_result TEXT, y15_status TEXT, y15_remark TEXT,
  y16_result TEXT, y16_status TEXT, y16_remark TEXT,
  y17_result TEXT, y17_status TEXT, y17_remark TEXT,
  y18_result TEXT, y18_status TEXT, y18_remark TEXT,
  y19_result TEXT, y19_status TEXT, y19_remark TEXT,
  y20_result TEXT, y20_status TEXT, y20_remark TEXT,
  y21_result TEXT, y21_status TEXT, y21_remark TEXT,
  y22_result TEXT, y22_status TEXT, y22_remark TEXT,
  y23_result TEXT, y23_status TEXT, y23_remark TEXT,
  y24_result TEXT, y24_status TEXT, y24_remark TEXT,
  y25_result TEXT, y25_status TEXT, y25_remark TEXT,
  y26_result TEXT, y26_status TEXT, y26_remark TEXT,
  y27_result TEXT, y27_status TEXT, y27_remark TEXT,
  y28_result TEXT, y28_status TEXT, y28_remark TEXT,
  y29_result TEXT, y29_status TEXT, y29_remark TEXT,
  y30_result TEXT, y30_status TEXT, y30_remark TEXT,
  y31_result TEXT, y31_status TEXT, y31_remark TEXT,
  y32_result TEXT, y32_status TEXT, y32_remark TEXT,
  y33_result TEXT, y33_status TEXT, y33_remark TEXT,
  y34_result TEXT, y34_status TEXT, y34_remark TEXT,
  y35_result TEXT, y35_status TEXT, y35_remark TEXT,
  y36_result TEXT, y36_status TEXT, y36_remark TEXT,
  y37_result TEXT, y37_status TEXT, y37_remark TEXT,
  y38_result TEXT, y38_status TEXT, y38_remark TEXT,
  y39_result TEXT, y39_status TEXT, y39_remark TEXT,
  y40_result TEXT, y40_status TEXT, y40_remark TEXT,
  y41_result TEXT, y41_status TEXT, y41_remark TEXT,
  y42_result TEXT, y42_status TEXT, y42_remark TEXT,
  y43_result TEXT, y43_status TEXT, y43_remark TEXT,
  y44_result TEXT, y44_status TEXT, y44_remark TEXT,
  y45_result TEXT, y45_status TEXT, y45_remark TEXT,
  y46_result TEXT, y46_status TEXT, y46_remark TEXT,
  y47_result TEXT, y47_status TEXT, y47_remark TEXT,
  y48_result TEXT, y48_status TEXT, y48_remark TEXT,
  y49_result TEXT, y49_status TEXT, y49_remark TEXT,
  y50_result TEXT, y50_status TEXT, y50_remark TEXT,
  y51_result TEXT, y51_status TEXT, y51_remark TEXT,
  y52_result TEXT, y52_status TEXT, y52_remark TEXT,
  y53_result TEXT, y53_status TEXT, y53_remark TEXT,
  y54_result TEXT, y54_status TEXT, y54_remark TEXT,
  y55_result TEXT, y55_status TEXT, y55_remark TEXT,
  y56_result TEXT, y56_status TEXT, y56_remark TEXT,
  y57_result TEXT, y57_status TEXT, y57_remark TEXT,
  y58_result TEXT, y58_status TEXT, y58_remark TEXT,
  y59_result TEXT, y59_status TEXT, y59_remark TEXT,
  y60_result TEXT, y60_status TEXT, y60_remark TEXT,
  y61_result TEXT, y61_status TEXT, y61_remark TEXT,
  y62_result TEXT, y62_status TEXT, y62_remark TEXT,
  y63_result TEXT, y63_status TEXT, y63_remark TEXT,
  y64_result TEXT, y64_status TEXT, y64_remark TEXT,
  INDEX idx_bmy_box_id (box_id),
  INDEX idx_bmy_created_time (created_time)
);
